# Generated by Django 4.0.4 on 2022-08-09 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eLearnApp', '0007_student_image_alter_course_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='image',
        ),
    ]
