# Generated by Django 4.0.4 on 2022-08-09 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eLearnApp', '0009_student_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='image',
        ),
    ]
