# Generated by Django 4.0.4 on 2022-08-09 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eLearnApp', '0011_student_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=None),
        ),
    ]
